"""add_stage2_testing_tables

Revision ID: d43a17720658
Revises: 55443d1dee2b
Create Date: 2025-09-17 14:21:43.541726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd43a17720658'
down_revision: Union[str, None] = '55443d1dee2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department_test_results',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stage2_answers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('participation_days', sa.String(length=10), nullable=True),
    sa.Column('participation_time', sa.String(length=20), nullable=True),
    sa.Column('general_q1_answer', sa.Text(), nullable=True),
    sa.Column('general_q1_time_taken', sa.Integer(), nullable=True),
    sa.Column('general_q2_answer', sa.Text(), nullable=True),
    sa.Column('general_q2_time_taken', sa.Integer(), nullable=True),
    sa.Column('general_q3_answer', sa.Text(), nullable=True),
    sa.Column('general_q3_time_taken', sa.Integer(), nullable=True),
    sa.Column('general_q4_answer', sa.Text(), nullable=True),
    sa.Column('general_q4_time_taken', sa.Integer(), nullable=True),
    sa.Column('general_q5_answer', sa.Text(), nullable=True),
    sa.Column('general_q5_time_taken', sa.Integer(), nullable=True),
    sa.Column('general_q6_answer', sa.Text(), nullable=True),
    sa.Column('general_q6_time_taken', sa.Integer(), nullable=True),
    sa.Column('general_questions_completed', sa.Boolean(), nullable=False),
    sa.Column('general_questions_started_at', sa.DateTime(), nullable=True),
    sa.Column('general_questions_completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('department_test_answers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('test_result_id', sa.BigInteger(), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('time_limit', sa.Integer(), nullable=False),
    sa.Column('time_taken', sa.Integer(), nullable=True),
    sa.Column('is_timeout', sa.Boolean(), nullable=False),
    sa.Column('correct_answer', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['test_result_id'], ['department_test_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department_test_answers')
    op.drop_table('stage2_answers')
    op.drop_table('department_test_results')
    # ### end Alembic commands ###
