"""add_stage2_submitted_to_users

Revision ID: eb8cbd883f2b
Revises: d43a17720658
Create Date: 2025-09-20 13:23:34.048714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb8cbd883f2b'
down_revision: Union[str, None] = 'd43a17720658'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('stage2_submitted', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'stage2_submitted')
    # ### end Alembic commands ###
