"""make_dormitory_nullable

Revision ID: 55443d1dee2b
Revises: 65abd21848ec
Create Date: 2025-09-11 14:39:33.607513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55443d1dee2b'
down_revision: Union[str, None] = '65abd21848ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'dormitory',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'dormitory',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
