"""add_new_fields_vsm_spbu_university

Revision ID: 65abd21848ec
Revises: 001_initial
Create Date: 2025-09-11 13:13:46.783837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65abd21848ec'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('is_from_vsm', sa.Boolean(), nullable=True))
    op.add_column('applications', sa.Column('is_from_spbu', sa.Boolean(), nullable=True))
    op.add_column('applications', sa.Column('university', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'university')
    op.drop_column('applications', 'is_from_spbu')
    op.drop_column('applications', 'is_from_vsm')
    # ### end Alembic commands ###
